const mongoose = require('mongoose');
const shortid = require('shortid');
const employeeSchema = new mongoose.Schema(
	{
		_id: { type: String, default: shortid.generate },
		id: { type: String, required: true },
		umcn: { type: String, default: '' },
		passport: { type: String, default: '' },
		firstName: { type: String, default: '' },
		lastName: { type: String, default: '' },
		middleName: { type: String, default: '' },
		typeReceiver: { type: String, default: '' },
		typeEmployment: { type: String, default: '' },
		typeEmployee: { type: String, default: '' },
		employmentUnit: { type: String, default: '' },
		employmentSection: { type: String, default: '' },
		employmentPosition: { type: String, default: '' },
		rating: { type: String, default: '' },
		group: { type: String, default: '' },
		realQualification: { type: String, default: '' },
		verifiedQualification: { type: String, default: '' },
		points: { type: String, default: '' },
		average1: { type: String, default: '' },
		average2: { type: String, default: '' },
		average3: { type: String, default: '' },
		allowanceMeal: { type: String, default: '' },
		allowanceInsurance: { type: String, default: '' },
		transportAllowanceCategory1: { type: String, default: '' },
		transportAllowanceCategory2: { type: String, default: '' },
		transportAllowanceCategory3: { type: String, default: '' },
		hours: { type: String, default: '' },
		amount: { type: String, default: '' },
		coefficient1: { type: String, default: '' },
		percentage: { type: String, default: '' },
		coefficient2: { type: String, default: '' },
		reducedYoS: { type: String, default: '' },
		muncipalityEmployment: { type: String, default: '' },
		muncipalityResidency: { type: String, default: '' },
		muncipalityPayout1: { type: String, default: '' },
		muncipalityPayout2: { type: String, default: '' },
		accountPayout1: { type: String, default: '' },
		accountPayout2: { type: String, default: '' },
		employmentBooklet_SerialNumber: { type: String, default: '' },
		employmentBooklet_RegistryNumber: { type: String, default: '' },
		employmentBooklet_DateOfIssue: { type: String, default: '' },
		employmentBooklet_Muncipality: { type: String, default: '' },
		employmentBooklet_EmploymentCode: { type: String, default: '' },
		externalYoS_periods: { type: Array, default: [] },
		externalYoS_total: { type: Number, default: 0 },
		internalYoS_periods: { type: Array, default: [] },
		internalYoS_total: { type: Number, default: 0 },
		totalYoS: { type: Number, default: 0 },
		address: { type: String, default: '' },
		zip: { type: String, default: '' },
		muncipality: { type: String, default: '' },
		sex: { type: String, default: '' },
		dateOfBirth: { type: String, default: '' },
		ID_serialNumber: { type: String, default: '' },
		ID_registryNumber: { type: String, default: '' },
		ID_dateOfIssue: { type: String, default: '' },
		ID_muncipalityOfIssue: { type: String, default: '' },
		HI_serialNumber: { type: String, default: '' },
		HI_registryNumber: { type: String, default: '' },
		HI_dateOfIssue: { type: String, default: '' },
		HI_muncipalityOfIssue: { type: String, default: '' },
		familyMembers: { type: String, default: '' },
		numberOfKids: { type: String, default: '' },
		email: { type: String, default: '' },
		comment: { type: String, default: '' }
	},
	{
		collection: 'employees'
	}
);
module.exports = mongoose.model('Employee', employeeSchema);
